/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JazzServer {
  static start(options: { appId: string; backendSecret: string; adminSecret: string; port?: number; dataDir?: string; inMemory?: boolean; jwksUrl?: string; jwtIssuer?: string; jwtAudience?: string; allowLocalFirstAuth?: boolean; upstreamUrl?: string; telemetryCollectorUrl?: string; schema?: Buffer | Uint8Array | number[] }): Promise<JazzServer>
  get appId(): string
  get url(): string
  get port(): number
  get dataDir(): string
  get backendSecret(): string
  get adminSecret(): string
  stop(): Promise<void>
}

export declare class NapiDb {
  /**
   * Exact wire capabilities compiled into this native binding.
   *
   * The TypeScript WebSocket carrier uses this for its Hello instead of an
   * independent feature list, so a package cannot advertise a codec this
   * native artifact cannot decode.
   */
  wireFeatures(): number
  requestInsertPermissionAdvice(table: string, cells: Uint8Array, author?: Uint8Array | undefined | null, claims?: JsonValue | undefined | null): string | PendingNativePermissionAdvice
  requestReadPermissionAdvice(table: string, rowId: Uint8Array, author?: Uint8Array | undefined | null, claims?: JsonValue | undefined | null): string | PendingNativePermissionAdvice
  requestUpdatePermissionAdvice(table: string, rowId: Uint8Array, patch: Uint8Array, author?: Uint8Array | undefined | null, claims?: JsonValue | undefined | null): string | PendingNativePermissionAdvice
  requestDeletePermissionAdvice(table: string, rowId: Uint8Array, author?: Uint8Array | undefined | null, claims?: JsonValue | undefined | null): string | PendingNativePermissionAdvice
  /** Admit a verified local-first account for this backend runtime only. */
  admitLocalFirstSession(token: string, appId: string, claimedAuthor: string): void
  insert(table: string, cells: Uint8Array, options?: InsertOptions | undefined | null): Write
  insertInTransaction(openTransactionId: string, table: string, cells: Uint8Array, options?: InsertOptions | undefined | null): Uint8Array
  update(table: string, rowId: Uint8Array, patch: Uint8Array, options?: UpdateOptions | undefined | null): Write
  updateInTransaction(openTransactionId: string, table: string, rowId: Uint8Array, patch: Uint8Array, options?: UpdateOptions | undefined | null): void
  /**
   * Binding-only entrypoint for typed partial-value updates. The public
   * TypeScript API validates column-kind-specific descriptors before they
   * reach this encoded boundary.
   */
  updateLargeValues(table: string, rowId: Uint8Array, patch: Uint8Array, mutations: JsonValue, updatedAtMs?: number | undefined | null): Write
  upsert(table: string, rowId: Uint8Array, cells: Uint8Array, options?: UpsertOptions | undefined | null): Write
  upsertInTransaction(openTransactionId: string, table: string, rowId: Uint8Array, cells: Uint8Array, options?: UpsertOptions | undefined | null): void
  delete(table: string, rowId: Uint8Array, options?: DeleteOptions | undefined | null): Write
  deleteInTransaction(openTransactionId: string, table: string, rowId: Uint8Array, options?: DeleteOptions | undefined | null): void
  restore(table: string, rowId: Uint8Array, cells?: Uint8Array | undefined | null, options?: RestoreOptions | undefined | null): Write
  restoreInTransaction(openTransactionId: string, table: string, rowId: Uint8Array, cells?: Uint8Array | undefined | null, options?: RestoreOptions | undefined | null): void
  beginStreamingMutation(table: string, rowId: Uint8Array, cells: Uint8Array, column: string, mutation?: string | undefined | null, author?: Uint8Array | undefined | null, attribution?: Uint8Array | undefined | null, updatedAtMs?: number | undefined | null, head?: JsonValue | undefined | null, base?: JsonValue | undefined | null): StreamingMutation
  static openMemory(schema: Uint8Array, config: Uint8Array): NapiDb
  /**
   * Open a deliberate backend runtime. Unlike the public raw-open entrypoint,
   * this explicit ABI derives the canonical system author.
   */
  static openMemoryAsBackend(schema: Uint8Array, config: Uint8Array): NapiDb
  /**
   * Open with a verified Jazz self-signed client identity. This is a
   * separate ABI entrypoint deliberately: a new client cannot accidentally
   * hand proof bytes to an old constructor, and an old client cannot enter
   * the proof-bearing path.
   */
  static openMemoryWithSelfSignedProof(schema: Uint8Array, config: Uint8Array, token: string, appId: string, claimedAuthor: string): NapiDb
  static openPersistent(dataPath: string, schema: Uint8Array, config: Uint8Array): NapiDb
  /**
   * Open a deliberate persistent backend runtime. This is intentionally a
   * distinct ABI from the public raw-open entrypoint.
   */
  static openPersistentAsBackend(dataPath: string, schema: Uint8Array, config: Uint8Array): NapiDb
  static openPersistentWithSelfSignedProof(dataPath: string, schema: Uint8Array, config: Uint8Array, token: string, appId: string, claimedAuthor: string): NapiDb
  /** Register and return a typed view backed by this same runtime owner. */
  registerSchema(schema: Uint8Array): NapiDb
  /** Begin one owner-wide transaction. */
  beginTransaction(openTransactionId: string, kind: string, author?: Uint8Array | undefined | null, attribution?: Uint8Array | undefined | null): void
  /** Commit an owner-wide transaction by id and optional kind. */
  commitTransaction(openTransactionId: string, kind?: string | undefined | null): Write
  /** Roll back an owner-wide open transaction by id. */
  rollbackTransaction(openTransactionId: string): void
  setTickScheduler(callback: ((err: Error | null, arg: string) => void)): void
  onMutationError(callback: (event: any) => void): void
  /**
   * Decode, prepare, and execute one read inside Rust. Query-plan ownership
   * never crosses the language boundary.
   */
  all(query: Uint8Array, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean; sync?: boolean } | undefined | null, openTransactionId?: string | undefined | null, author?: Uint8Array | undefined | null, claims?: JsonValue | undefined | null): Uint8Array | PendingNativeRead
  /** Bind receipt-correlation claims to this client's own admitted identity. */
  setSessionClaims(claims?: Record<string, unknown> | undefined | null): void
  /**
   * Set ambient claims for mutation and other explicitly serialized
   * identity operations. Prepared queries capture scoped identity and
   * claims at preparation time, so concurrent reads do not consult this
   * shared map.
   */
  setIdentityClaims(author: Uint8Array, claims?: Record<string, unknown> | undefined | null): void
  localCurrentRow(table: string, rowId: Uint8Array): Uint8Array
  subscribe(query: Uint8Array, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null, author?: Uint8Array | undefined | null, claims?: JsonValue | undefined | null): Subscription | PendingNativeSubscription
  tick(): void
  /** Configure Jazz-owned upload ingress and unpublished-tree expiry limits. */
  setLargeValueStagingPolicy(incomingBytesPerWindow: number, windowMs: number, maxAgeMs?: number | undefined | null): void
  /** Run one idempotent expiry pass; native hosts normally call this on a timer. */
  evictExpiredStagedLargeValues(): number
  setNonDurableClient(): void
  connectUpstream(): Transport
  connectUpstreamWithSession(protocolVersion: number, features: number, remoteNode: Buffer, remoteEpoch: bigint, localNode: Buffer, localEpoch: bigint): Transport
  /** Return the originating node clock before a host releases its memory runtime. */
  foregroundTxTimeHighWater(): bigint
  /** Merge a checked host-retained node clock before opening new local writes. */
  seedForegroundTxTimeHighWater(highWater: bigint): void
  waitForPendingWrites(tier: string): Uint8Array | PendingNativeRead
  close(): Promise<undefined>
}

/**
 * A JavaScript-thread-owned permission preflight which is waiting for an
 * authenticated upstream authority.  Like pending reads, this remains on the
 * owning JavaScript thread: NAPI's worker-pool promises require `Send`, while
 * the request future deliberately owns thread-affine connection state.
 */
export declare class PendingNativePermissionAdvice {
  poll(): string | null
  cancel(): void
}

/**
 * A JavaScript-thread-owned binding read waiting for query coverage or
 * asynchronous large-value storage. NAPI promises execute on a Send worker
 * pool, whereas a Jazz runtime is deliberately `Rc`/thread-affine. The
 * adapter drives this object after its peer transport makes progress instead
 * of blocking Node.
 */
export declare class PendingNativeRead {
  poll(): Uint8Array | null
}

/** Thread-affine subscription opening waiting for the core owner. */
export declare class PendingNativeSubscription {
  setWake(callback: ((err: Error | null, arg: string) => void)): void
  poll(): Subscription | null
  cancel(): void
}

/**
 * Opaque marker returned while the next bounded native subscription batch is
 * waiting for chunk I/O. Call `readAll` again after transport progress.
 */
export declare class PendingNativeSubscriptionBatch {
  /**
   * The host should wait this bounded delay before asking the subscription
   * to retry a retained chunk-hydration batch.
   */
  retryAfterMs(): number | null
}

/**
 * Native bounded-memory sink used by the TypeScript async streaming-mutation
 * adapter. Each push incrementally prepares and stages bounded Groove nodes,
 * using the same ingress policy and resumable construction as WASM.
 */
export declare class StreamingMutation {
  push(chunk: Uint8Array): void
  finish(): Write
  abort(): boolean
}

export declare class Subscription {
  readAll(): Array<SubscriptionEvent> | PendingNativeSubscriptionBatch
  drain(): Array<SubscriptionEvent> | PendingNativeSubscriptionBatch
  close(): boolean
}

export declare class TestJwtIssuer {
  static start(): Promise<TestJwtIssuer>
  get jwksUrl(): string
  get issuer(): string
  get audience(): string
  jwtForUser(userId: string, claims?: Record<string, unknown> | undefined, options?: { expiresInSeconds?: number; issuer?: string } | undefined): string
  stop(): Promise<void>
}

export declare class Transport {
  routeAuxiliaryWireFrame(frame: Uint8Array): Uint8Array | null
  recvAuxiliaryWireFrames(): Array<Uint8Array>
  auxiliaryOutboundReady(): boolean
  sendWireFrame(frame: Uint8Array): void
  sendWireFrames(frames: Array<Uint8Array>): void
  recvWireFrames(): Array<Uint8Array>
  tick(): number
  close(): boolean
}

export declare class Write {
  get txId(): string
  get payload(): Uint8Array
  get rowId(): Uint8Array
  writeState(): any
  wait(tier: string): Promise<undefined>
  close(): boolean
}

export interface DeleteOptions {
  author?: Uint8Array
  attribution?: Uint8Array
  head?: JsonValue
  base?: JsonValue
  updatedAtMs?: number
}

export interface InsertOptions {
  rowId?: Uint8Array
  author?: Uint8Array
  attribution?: Uint8Array
  branch?: JsonValue
  updatedAtMs?: number
}

/**
 * Any JSON-compatible value crossing the native JavaScript boundary.
 *
 * Keep this alias exported through napi-rs rather than relying on its Rust
 * import name: exported methods use `JsonValue` throughout their generated
 * declarations, so the package must define that name for TypeScript
 * consumers.
 */
export type JsonValue =
  any

export declare function mintLocalFirstToken(seedB64: string, audience: string, ttlSeconds: number): string

/** Exact build/ABI fingerprint for the generated native artifact. */
export declare function nativeArtifactFingerprint(): string

export interface RestoreOptions {
  author?: Uint8Array
  attribution?: Uint8Array
  branch?: JsonValue
  updatedAtMs?: number
}

export interface SubscriptionClosedEvent {
  type: 'closed'
}

export interface SubscriptionDeltaEvent {
  type: 'delta'
  reset: boolean
  delta: Uint8Array
  terminalOperations: Array<SubscriptionTerminalOperation>
  settled: boolean
  tier: 'None' | 'Local' | 'Edge' | 'Global'
}

export type SubscriptionEvent =
  SubscriptionDeltaEvent | SubscriptionRejectedEvent | SubscriptionClosedEvent

export interface SubscriptionInvalidAuthoritySourceClosureReason {
  type: 'InvalidAuthoritySourceClosure'
  transition: string
}

export interface SubscriptionRejectedEvent {
  type: 'rejected'
  reason: SubscriptionRejectionReason
}

export type SubscriptionRejectionReason =
  SubscriptionUnsupportedShapeCapabilityReason | SubscriptionShapeRegistrationPendingReason | SubscriptionServerFailureReason | SubscriptionInvalidAuthoritySourceClosureReason

export interface SubscriptionServerFailureReason {
  type: 'ServerFailure'
  code: 'TableNotFound' | 'SchemaResolution' | 'QueryValidation' | 'QueryLowering' | 'PolicyEvaluation' | 'Internal'
}

export interface SubscriptionShapeRegistrationPendingReason {
  type: 'ShapeRegistrationPendingCatalogueAdmission'
}

export interface SubscriptionTerminalCollectionPathSegment {
  Collection: string
}

export type SubscriptionTerminalEdit =
  SubscriptionTerminalInsertEdit | SubscriptionTerminalUpdateEdit | SubscriptionTerminalRemoveEdit | SubscriptionTerminalMoveEdit

export interface SubscriptionTerminalInsert {
  index: number
  key: Array<number>
  value: Array<number>
}

export interface SubscriptionTerminalInsertEdit {
  Insert: SubscriptionTerminalInsert
}

export interface SubscriptionTerminalKeyPathSegment {
  Key: Array<number>
}

export interface SubscriptionTerminalMove {
  key: Array<number>
  index: number
}

export interface SubscriptionTerminalMoveEdit {
  Move: SubscriptionTerminalMove
}

export interface SubscriptionTerminalOperation {
  root_key: Array<number>
  path: Array<SubscriptionTerminalPathSegment>
  edit: SubscriptionTerminalEdit
}

export type SubscriptionTerminalPathSegment =
  SubscriptionTerminalCollectionPathSegment | SubscriptionTerminalKeyPathSegment

export interface SubscriptionTerminalRemove {
  key: Array<number>
}

export interface SubscriptionTerminalRemoveEdit {
  Remove: SubscriptionTerminalRemove
}

export interface SubscriptionTerminalUpdate {
  key: Array<number>
  value: Array<number>
}

export interface SubscriptionTerminalUpdateEdit {
  Update: SubscriptionTerminalUpdate
}

export interface SubscriptionUnsupportedShapeCapabilityReason {
  type: 'UnsupportedShapeCapability'
  detail: string
}

export interface UpdateOptions {
  author?: Uint8Array
  attribution?: Uint8Array
  head?: JsonValue
  base?: JsonValue
  updatedAtMs?: number
}

export interface UpsertOptions {
  author?: Uint8Array
  attribution?: Uint8Array
  head?: JsonValue
  base?: JsonValue
  updatedAtMs?: number
}

export declare function verifyLocalFirstIdentityProof(token: string | undefined | null, expectedAudience: string): VerifyTokenResult

export interface VerifyTokenResult {
  ok: boolean
  id: string
  error?: string
}
