/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DevServer {
  static start(options: { appId: string; port?: number; dataDir?: string; inMemory?: boolean; jwksUrl?: string; allowLocalFirstAuth?: boolean; backendSecret?: string; adminSecret?: string; catalogueAuthority?: 'local' | 'forward'; catalogueAuthorityUrl?: string; catalogueAuthorityAdminSecret?: string; telemetryCollectorUrl?: string }): Promise<DevServer>
  get appId(): string
  get url(): string
  get port(): number
  get dataDir(): string
  get backendSecret(): string | null
  get adminSecret(): string | null
  stop(): Promise<void>
}

export declare class NapiRuntime {
  /** Create a new NapiRuntime with SQLite-backed persistent storage. */
  constructor(schemaJson: string, appId: string, jazzEnv: string, userBranch: string, dataPath: string, tier?: string | undefined | null)
  /** Create a new NapiRuntime with in-memory storage (no local persistence). */
  static inMemory(schemaJson: string, appId: string, jazzEnv: string, userBranch: string, tier?: string | undefined | null): NapiRuntime
  insert(table: string, values: Record<string, unknown>, objectId?: string | undefined | null): any
  insertWithSession(table: string, values: Record<string, unknown>, writeContextJson?: string | undefined | null, objectId?: string | undefined | null): any
  update(objectId: string, values: any): any
  updateWithSession(objectId: string, values: any, writeContextJson?: string | undefined | null): any
  delete(objectId: string): any
  deleteWithSession(objectId: string, writeContextJson?: string | undefined | null): any
  loadLocalBatchRecord(batchId: string): any | null
  loadLocalBatchRecords(): any[]
  drainRejectedBatchIds(): string[]
  acknowledgeRejectedBatch(batchId: string): boolean
  sealBatch(batchId: string): void
  query(queryJson: string, sessionJson?: string | undefined | null, tier?: string | undefined | null, optionsJson?: string | undefined | null): Promise<any>
  subscribe(queryJson: string, onUpdate: (...args: any[]) => any, sessionJson?: string | undefined | null, tier?: string | undefined | null, optionsJson?: string | undefined | null): number
  unsubscribe(handle: number): void
  /** Phase 1 of 2-phase subscribe: allocate a handle and store query params. */
  createSubscription(queryJson: string, sessionJson?: string | undefined | null, tier?: string | undefined | null, optionsJson?: string | undefined | null): number
  /** Phase 2 of 2-phase subscribe: compile, register, sync, attach callback, tick. */
  executeSubscription(handle: number, onUpdate: (...args: any[]) => any): void
  onSyncMessageReceived(messageJson: string, sequence?: number | undefined | null): void
  /** Called by JS when a sync message arrives from a client (not a server). */
  onSyncMessageReceivedFromClient(clientId: string, messageJson: string): void
  addServer(serverCatalogueStateHash?: string | undefined | null, nextSyncSeq?: number | undefined | null): void
  removeServer(): void
  addClient(): string
  /** Set a client's role ("user", "admin", or "peer"). */
  setClientRole(clientId: string, role: string): void
  getSchema(): any
  getSchemaHash(): string
  flush(): void
  /** Flush and close the underlying storage, releasing filesystem locks. */
  close(): void
  static deriveUserId(seedB64: string): string
  static mintLocalFirstToken(seedB64: string, audience: string, ttlSeconds: number): string
  static getPublicKeyBase64url(seedB64: string): string
  /**
   * Connect to a Jazz server over WebSocket.
   *
   * Parses `auth_json` into `AuthConfig`, wires a `TransportManager` into
   * `RuntimeCore` via `install_transport` (which seeds the catalogue state
   * hash on the handle), and spawns the manager loop as a Tokio task.
   */
  connect(url: string, authJson: string): void
  /** Disconnect from the Jazz server and drop the transport handle. */
  disconnect(): void
  /** Push updated auth credentials into the live transport. */
  updateAuth(authJson: string): void
  /**
   * Register a JS callback that fires when the Rust transport receives an
   * auth rejection from the server during the WS handshake.
   *
   * The callback receives a single string argument: the rejection reason.
   */
  onAuthFailure(callback: (reason: string) => void): void
}

export declare class TestingServer {
  static start(options?: { appId?: string; port?: number; dataDir?: string; persistentStorage?: boolean; adminSecret?: string; backendSecret?: string; jwksUrl?: string }): Promise<TestingServer>
  get appId(): string
  get url(): string
  get port(): number
  get dataDir(): string
  get backendSecret(): string
  get adminSecret(): string
  jwtForUser(userId: string, claims?: Record<string, unknown> | undefined): string
  stop(): Promise<void>
}

export declare function currentTimestamp(): number

export declare function deriveUserId(seedB64: string): string

export declare function generateId(): string

export declare function getPublicKeyBase64url(seedB64: string): string

export declare function mintLocalFirstToken(seedB64: string, audience: string, ttlSeconds: number): string

export declare function parseSchema(json: string): any

export declare function verifyLocalFirstIdentityProof(token: string | undefined | null, expectedAudience: string): VerifyTokenResult

export interface VerifyTokenResult {
  ok: boolean
  id: string
  error?: string
}
